### ISSUE TITLE
FRP: Gnosis batched TX

### ISSUE THREAD

**Issue by Majorfi** [yearn/yearn.fi#113]
### What is your proposal 🚀
With a Gnosis safe transactions can be batched and triggered all at once. We should use this in the action flow when using a gnosis safe as wallet.

### What does this solve ? 🛠
Make it more gas efficient and easier for Safe to interact with

### More 🔎
*N/A*

**Comment by 0xBasically** [comment]
Moved the estimated date to finish back @karelianpie can we get this done in a month or two? Is this something you are comfortable working on?

**Comment by karelianpie** [comment]
> Moved the estimated date to finish back @karelianpie can we get this done in a month or two? Is this something you are comfortable working on?

@0xBasically I appreciate you assigning me everywhere :) but I can assign myself when I pick up an issue. This one I had a look and I'm not sure what the idea is completely.

I think estimates should be done by the engineering team, as only them can do the work and know what is involved. As far as I know we're not doing estimations, we just take work as it comes as we're a small team.
