### ISSUE TITLE
Chore: Ensure safeChainID

### ISSUE THREAD

**Issue by Majorfi** [yearn/yearn.fi#124]
### What happened 🆘
The behavior between `safeChainID` and `vaultChainID` can be unexpected when the user is connected on mainnet (for ex) but on the page for a vault on optimism (for ex). For actions related to this vault chainID, we need to ensure we are using the `vaultChainID` rather than the `safeChainID`

### To Reproduce 🔂
NA

### More 🔎
NA

**Comment by karelianpie** [comment]
TODO: Disabling the action buttons when the user is in a different network than the vault
