### ISSUE TITLE
Bug: UI showing incorrect earned amount

### ISSUE THREAD

**Issue by defiglenn** [yearn/yearn.fi#199]
### What happened 🆘
Yearn.finance showing incorrect 'earned' amount for vault token holders. 

- Balance is sometimes showing 0 amount when user had previously seen earned amount above 0. https://discord.com/channels/734804446353031319/734811808401063966/1109253025958211675
- Balance sometimes showing negative amount after user deposits
- https://discord.com/channels/734804446353031319/734811808401063966/1109253025958211675
- Balance not increasing after a harvest has taken place. A user reported to me on telegram how, despite a harvest completing 10 hours ago where the share price on yearn.vision had increased, his earned amount was unchanged.

### To Reproduce 🔂
View earned amount in vault, see how it changes after a deposit and harvest

**Comment by karelianpie** [comment]
@Majorfi do you think these issues are coming from yDaemon or even more upstream?

**Comment by karelianpie** [comment]
@Majorfi @defiglenn I'm closing this one here and opening one in yDaemon repo https://github.com/yearn/ydaemon/issues/277
