### ISSUE TITLE
Bug: Error 404 on wFTM vault

### ISSUE THREAD

**Issue by Majorfi** [yearn/yearn.fi#200]
### What happened 🆘
A user reported an error 404 on this page: https://yearn.finance//vaults/250/0x0DEC85e74A92c52b7F708c4B10207D9560CEFaf0

Report submitted ~20mn ago

### To Reproduce 🔂
Couldn't reproduce

### More 🔎
I suspect some error on the address check on the getServerSide stuff

**Comment by karelianpie** [comment]
Closing as I believe this was an isolated issue, I think the user managed to access the vault in the end https://ftmscan.com/tx/0xd6b91033c4560b749df363f70a0478ee3eb0b5466a2f0748e51812c5bf193aab
