### ISSUE TITLE
feat: refactor wrappers

### ISSUE THREAD

**Issue by Majorfi** [yearn/yearn.fi#218]
These wrappers seem all the same, the only thing changing is the context.

Do we want to extract this to its own component that just takes the context?

_Originally posted by @karelianpie in https://github.com/yearn/yearn.fi/pull/214#discussion_r1212725002_

**Comment by karelianpie** [comment]
Closing as I had a look at this one and it's a bit more complex that it seemed at first glance, each of these wrappers is being wrapped sometimes by another context that changes from app to app
