### ISSUE TITLE
Fix: Catch tx fails with sentry

### ISSUE THREAD

**Issue by Majorfi** [yearn/yearn.fi#221]
We could throw here if `receipt.status === 'success'` so we log this in Sentry

I feel in many places we are expecting the happy path, maybe sending to Sentry is a good first step then we can try and handle the errors a bit better

_Originally posted by @karelianpie in https://github.com/yearn/yearn.fi/pull/205#discussion_r1213004356_

**Comment by karelianpie** [comment]
Closing as these are already thrown
