### ISSUE TITLE
Bug: OpBoost staking indicator

### ISSUE THREAD

**Issue by Majorfi** [yearn/yearn.fi#240]
### What happened 🆘
On Optimism, when the OP boost is used, the tokens are not deposited but stacked in another contract. Because of that, users need to go in a separate tab (OP Boost) to see both their deposit + the withdrawal actions.
We should display a warning, a message or an indicator, mostly on mobile, indicating that x tokens are staked and can be withdrawn on the opboost tab

**Comment by karelianpie** [comment]
> We should display a warning, a message or an indicator, mostly on mobile, indicating that x tokens are staked and can be withdrawn on the opboost tab

Should we get designs for this?

**Comment by karelianpie** [comment]
Copy
> **Dude where's my rewards?** You have XX waiting for you in the OP BOOST tab (yep, the one just above here).
