### ISSUE TITLE
Bug: Can not connect to Metamask

### ISSUE THREAD

**Issue by caotrongtin99** [yearn/yearn.fi#265]
Hi @Majorfi
### What happened 🆘
No event occurs when I click on Metamask in Login Modal
### To Reproduce 🔂
1. Open https://yearn.finance/ in a browser tab
2. Wait for the page to finish loading
3. Copy [https://yearn.finance/](https://yearn.finance/)
4. Open another tab and paste the URL
5. Click Connect Wallet then Click Metamask 
6. If it works fine, redo step 4
### More 🔎
- Browser : Chrome v114

**Comment by caotrongtin99** [comment]
Hi @Majorfi 
Thanks for the information. I have just tested on https://yearn.finance/ and see that the error is still there

**Comment by caotrongtin99** [comment]
Hi @Majorfi 
This is on my side [https://drive.google.com/file/d/1FX3CNFtRmDWi1LtzRN1taiz9_XjkEW9r/view?usp=sharing](https://drive.google.com/file/d/1FX3CNFtRmDWi1LtzRN1taiz9_XjkEW9r/view?usp=sharing)

Could you help me check that? Thanks a lot

**Comment by caotrongtin99** [comment]
<img width="1436" alt="Screen Shot 2023-07-04 at 16 40 24" src="https://github.com/yearn/yearn.fi/assets/35460708/5476402e-de90-48ae-82b6-223dacdbccd6">
Nothing happens, but there are a lot of websocket connection errors @Majorfi

**Comment by caotrongtin99** [comment]
Yes, i still have this issue. Maybe window.ethereum is undefined so `requestAccounts` method will not work

**Comment by 0xBasically** [comment]
@karelianpie do you have time to take a look here?

**Comment by karelianpie** [comment]
@caotrongtin99 you appear to have quite many extensions, can you try disabling them and trying again? I'm afraid some extension is not allowing you to connect your wallet.

**Comment by 0xBasically** [comment]
or try allowing metamask on incognito mode and try in that mode to connect

**Comment by karelianpie** [comment]
I'm going to close this for now, it appears to be an isolated case. However, @caotrongtin99 feel free to reopen if you're able to reproduce this with your extensions disabled. We just need a way to reproduce, at the moment I'm unable to do so.
