### ISSUE TITLE
Bug: UI issue with deposited amount not showing

### ISSUE THREAD

**Issue by defiglenn** [yearn/yearn.fi#269]
### What happened 🆘
Not showing deposit amount on UI

### To Reproduce 🔂
Deposit into an Optimism vault and see if the deposit amount shows under 'holdings' and when clicking through to the vault in question

### More 🔎
![image](https://github.com/yearn/yearn.fi/assets/86468557/6e421c3e-3e18-4050-9278-e070253ed4e0)

**Comment by karelianpie** [comment]
Closing this as it's related to https://github.com/yearn/yearn.fi/issues/267

The deposited amount is too small for the current value to display. A hot fix is already pushed.

cc @Majorfi
