### ISSUE TITLE
FRP: Revamp the default vault filtering and search

### ISSUE THREAD

**Issue by simonbdefi** [yearn/yearn.fi#272]
### What is your proposal 🚀

Look into optimizing the default 'Vaults' page user flow, possibly defaulting to displaying all vaults sorted by TVL.

### What does this solve ? 🛠

The `Vaults` page currently defaults to the `Featured` tab, with the search bar look-up solely in that category. Recent feedback received from users and partners indicates that this might be problematic, namely;

1- Users use the search bar from the default page, not finding the vault they are looking for (look-up only within 'Featured'). 

![image](https://github.com/yearn/yearn.fi/assets/98047648/d559296c-d36f-4b06-80fd-3474c46e8ebc)

2- Users might not see the different filtering tabs.

### More 🔎
*N/A*

**Comment by karelianpie** [comment]
@0xValJohn we (Facu, Evan and I) think that swapping the category and search would help with this issue. As in, we'd move the search to the right and the categories to the left. What are your thoughts on this?
