### ISSUE TITLE
feat: add services' page for related projects

### ISSUE THREAD

**Issue by 0xBasically** [yearn/yearn.fi#275]
add a separate page for other services not listed on the main page.

**Comment by Wholesomebruh** [comment]
Hey @0xBasically , please elaborate the issue. What other services are you talking about?

**Comment by 0xBasically** [comment]
It would be a page to hold other things related to yearn, such as yaudit.dev maybe yearn.world, buyback.yearn.finance. Not 100% where or how it would be displayed, as a link on the homepage or another icon possibly.

**Comment by karelianpie** [comment]
@0xBasically will close this for now as there seems to be some resistance to add more links --
