### ISSUE TITLE
Bug: copy for migration in holdings can be improved

### ISSUE THREAD

**Issue by saltyfacu** [yearn/yearn.fi#300]
### What happened 🆘
The copy can be improved. It sounds weird right now.
Change "Looks like you're holding tokens for an old version..." to "Looks like you're holding tokens from a previous version..."
Also remove caps from the word "Vaults", all lowercase

### To Reproduce 🔂
- Use this wallet (0x05c31f9623A5b691F18e60e68F23C64cD708Badb) as watch-only
- Go to https://yearn.finance/vaults
- Select Holdings

![IMAGE 2023-07-26 12:41:41](https://github.com/yearn/yearn.fi/assets/839844/0a6e95f4-024a-46be-a2ed-5468232b59b5)

**Comment by saltyfacu** [comment]
Hey, @lazyfuhrer ! That's cool! Please do :)

**Comment by lazyfuhrer** [comment]
You can assign me @saltyfacu

**Comment by lazyfuhrer** [comment]
check #305
