### ISSUE TITLE
[EXT-9] Feature request: change factory page so it can display other factories, velo, bal

### ISSUE THREAD

**Issue by 0xBasically** [yearn/yearn.fi#314]
### What happened 🆘
Factory page is hard-coded to eth curve factory but we have other factories. We should figure out how to display them on the factory page.

### To Reproduce 🔂
![image](https://github.com/yearn/yearn.fi/assets/131375535/51482b42-b2a1-4c61-8028-8207c4a330d7)

### More 🔎
- Browser : 

<sub>[EXT-9](https://linear.app/fancy-xopowo/issue/EXT-9/feature-request-change-factory-page-so-it-can-display-other-factories)</sub>

**Comment by karelianpie** [comment]
> We should figure out how to display them on the factory page.

There's not enough information to address this issue as is, wondering who has the context about this?

**Comment by saltyfacu** [comment]
Checked with @0xBasically, this should be closed.
