### ISSUE TITLE
Bug: deprecated vault not shown in holdings

### ISSUE THREAD

**Issue by saltyfacu** [yearn/yearn.fi#320]
### What happened 🆘
When you have funds in a deprecated vault in optimism and those are staked in for OP rewards, it's not shown in holdings

### To Reproduce 🔂
using this address: `0x4FfD0A59a26cB2Aa76D403215e4cC2845C053994`, check the Velo wUSDR/USDC vault.

**Comment by karelianpie** [comment]
Is that address still valid? I'm unable to see anything staked in for OP rewards @saltyfacu 

Velodrome wUSDR-USDC, account `0x4FfD0A59a26cB2Aa76D403215e4cC2845C053994`

<img width="1036" alt="Screenshot 2023-08-13 at 17 45 42" src="https://github.com/yearn/yearn.fi/assets/78794805/3759a999-5557-4f61-8135-1278b5f103fb">

**Comment by saltyfacu** [comment]
Hey, thanks for the answer. I think you might be looking at the wrong vault or the owner withdrew. 

I've checked with another address and it's already working. Thanks ser for checking this out!

**Comment by karelianpie** [comment]
> Hey, thanks for the answer. I think you might be looking at the wrong vault or the owner withdrew.

Yeah I think they withdrew

> I've checked with another address and it's already working. Thanks ser for checking this out!

🎉
