### ISSUE TITLE
Bug: cowswap zap not working as intended

### ISSUE THREAD

**Issue by 0xBasically** [yearn/yearn.fi#339]
### What happened 🆘
when choosing cowswap on this vault `0x849dC56ceCa7Cf55AbF5ec87910DA21c5C7dA581` at least, it says all tokens that are able to be zapped into  are "Uncaught (in promise) AssertionError [ERR_ASSERTION]: Input token is not supported by Cowswap". Also the approve button gives no errors to the user it should saying why it failed. 

### To Reproduce 🔂
try to zap via cowswap check console

**Comment by karelianpie** [comment]
@0xBasically are you reporting that zapping doesn't work at all or just cowswap? The flow for zapping is such that if one fails then it will move to the next one. Errors in the console can be safely ignored.

**Comment by 0xBasically** [comment]
cowswap wasnt working specifically also I dont think it did move on to the next one

**Comment by karelianpie** [comment]
> cowswap wasnt working specifically also I dont think it did move on to the next one

Can you give me the wallet that you've tried that on? So the approve failed silently?

**Comment by 0xBasically** [comment]
> > cowswap wasnt working specifically also I dont think it did move on to the next one
> 
> Can you give me the wallet that you've tried that on? So the approve failed silently?

you can try it on any wallet it never even gets sent

**Comment by karelianpie** [comment]
> you can try it on any wallet it never even gets sent

I'm unable to repro, can you make a screen recording of this issue if you're able to repro again? 🙇

**Comment by 0xBasically** [comment]
seems to be working atm cant see the same issue
