### ISSUE TITLE
Bug: bridged USDC is now called USDC.e

### ISSUE THREAD

**Issue by saltyfacu** [yearn/yearn.fi#340]
### What happened 🆘
The USDC vaults should be the USDC.e vault. The name changed, there's a native USDC version now.
We should change it everywhere.

### To Reproduce 🔂
Go here: https://yearn.fi/vaults/10/0xaD17A225074191d5c8a37B50FdA1AE278a2EE6A2
Check the token in the vault contract. The token name changed.

**Comment by karelianpie** [comment]
Created X that renames USDC to USDC.e in the only place in the app that hardcoded the symbol name, all the rest comes downstream, @Majorfi is it hardcoded in yDaemon?

**Comment by karelianpie** [comment]
Closing as there's nothing hardcoded in yearn.fi -- @Majorfi do you mind checking downstream?

**Comment by karelianpie** [comment]
@saltyfacu will follow up here, the hardcoded label might be in yDaemon or even more upstream

**Comment by 0xBasically** [comment]
This is not a website issue but yDaemon issue

**Comment by saltyfacu** [comment]
Created the issue in yDaemon: https://github.com/yearn/ydaemon/issues/331
