### ISSUE TITLE
Bug: wrong, crazy high 'deposited' numbers showing 

### ISSUE THREAD

**Issue by defiglenn** [yearn/yearn.fi#348]
### To Reproduce 🔂
connect wallet on yearn.fi on mobile to OP 
visit vaults page, see if number at top for 'Deposited' accurately reflects amount user has deposited in vaults

### More 🔎
- https://discord.com/channels/734804446353031319/734862139386232902/1151461519758995456
- https://discord.com/channels/734804446353031319/734862139386232902/1151477357010489376

**Comment by karelianpie** [comment]
@defiglenn do we have an example address to try and reproduce this?

**Comment by 0xBasically** [comment]
reopened under ydaemon repo https://github.com/yearn/ydaemon/issues/322
