### ISSUE TITLE
Enhancement: blockchain selection is not consistent across pages

### ISSUE THREAD

**Issue by saltyfacu** [yearn/yearn.fi#350]
### What happened 🆘
- I choose base
- connect my wallet
- click on vaults
- I’m on ethereum again 😅 

### To Reproduce 🔂
- Follow steps above

**Comment by karelianpie** [comment]
@Majorfi, are you sure this is ready for TODO? @saltyfacu said that he would investigate this more and then come up with a solution -- so I've assigned this to him instead

**Comment by saltyfacu** [comment]
This has been superseded by removí by the chain selector
