### ISSUE TITLE
Bug: We don't have Curve and Balancer on Base

### ISSUE THREAD

**Issue by saltyfacu** [yearn/yearn.fi#352]
### What happened 🆘
There are sections for curve and balancer on the vaults' list

### To Reproduce 🔂
- Go to: https://yearnfi-git-feat-base.yearn.farm/vaults
- Check sections

### More 🔎
- Browser :

**Comment by karelianpie** [comment]
> Fixed with [900fe36](https://github.com/yearn/yearn.fi/commit/900fe362f5f93330b98f6095c99e549dae509feb)

Closable?
