### ISSUE TITLE
Bug: Incorrect total assets shown on TricryptoINV vault

### ISSUE THREAD

**Issue by wavey0x** [yearn/yearn.fi#378]
### What happened 🆘
When visiting the web page to view TricryptoINV vault (0x6949145469362F9eeaB3c96Ea41b51D9B4cC2b21) it shows the correct pricing, but 0 TVL. It should show 
![image](https://github.com/yearn/yearn.fi/assets/82397455/6613c5fa-7219-41f2-8a1e-3a7c487afd6a)

I assume this field should contain `vault.totalAssets()`. 
According to chain (and even yDaemon), the correct amount of tokens should be 1841.13690834 or `"total_assets": "1841136908338691674686"`

https://ydaemon.yearn.fi/1/vaults/all?hideAlways=true&orderBy=apy.net_apy&orderDirection=desc&strategiesDetails=withDetails&strategiesRisk=withRisk&strategiesCondition=inQueue

### To Reproduce 🔂
visit https://yearn.fi/vaults/1/0x6949145469362F9eeaB3c96Ea41b51D9B4cC2b21?tab=about

**Comment by saltyfacu** [comment]
Thanks. This was happening from time to time. Today we are publishing an update that should fix it

**Comment by saltyfacu** [comment]
Now it's showing the correct amount. I'll close the issue :) 

<img width="247" alt="Screenshot 2023-10-20 at 10 21 30" src="https://github.com/yearn/yearn.fi/assets/839844/2e756c06-8a43-40db-8576-a86da8faaaac">
