### ISSUE TITLE
[EXT-7] FRP: [veYFI] improve hierarchy

### ISSUE THREAD

**Issue by 0x7171** [yearn/yearn.fi#384]
#### Current design

<img width="912" alt="Screen Shot 2023-10-17 at 15 41 26" src="https://github.com/yearn/yearn.fi/assets/91192250/0564bbf4-93e3-4843-be43-fa6228ed536e">

Top nav:
- Home
- veYFI
- Docs

Tab navigation:
- 7 different tabs:
   - Lock YFI
   - Manage lock
   - Claim
   - Stake/Unstake
   - Rewards
   - Redeem dYFI
   - Vote for gauge 
- Conflicting naming such as "Claim" and "Rewards"

#### Proposed design
This proposal simplifies the structure as follows:

**Top nav:**
- Home
- veYFI
- Gauges
- dYFI
- Vote
- Docs

**veYFI:**
Has tab bar:
- Lock YFI
- Manage lock
   - Extend lock
   - Early exit
   - Withdraw expired lock 
- Claim
   - Boost rewards (paid as dYFI)
   - Early exit rewards (paid as YFI)

**Gauges:**
Has tab bar:
- Stake / Unstake
- Claim

**dYFI:**
No tab bar, displays only Redeem design

**Vote:**
No tab bar, displays only Vote design

### What does this solve ? 🛠
- Makes navigation clearer
- Separates use cases in distinct areas
- Removes confusing wording
- Handles missing use cases (claim veYFI early exit and boost rewards)

### More 🔎
*N/A*

<sub>[EXT-7](https://linear.app/fancy-xopowo/issue/EXT-7/frp-[veyfi]-improve-hierarchy)</sub>

**Comment by rossgalloway** [comment]
I was going to work on this issue but upon reviewing it I would recommend that it either be closed or reconsidered as similar changes have been made to the live website.

### Live Design
The live design is as a follows:

#### Top Nav
- Home
- veYFI
- Docs

#### veYFI:
has tab bar:

- Manage Gauges
  - Stake/Unstake (from gauges)
  - Vote for Gauge
- Manage veYFI
  - Lock YFI
  - Extend Lock
  - Early Exit
  - Claim Expired Lock
- Claim Rewards
  - Gauge Rewards
  - veYFI Boost Rewards
  - veYFI Exit Rewards
- Redeem dYFI
  - Redeem

The live design satisfies the criteria listed above that is being solved for:

> What does this solve ? 🛠
> - Makes navigation clearer
> - Separates use cases in distinct areas
> - Removes confusing wording
> - Handles missing use cases (claim veYFI early exit and boost rewards)

It does so fully using the tabs, which is cleaner than both tabs and top nav. The only element I see that maybe would want its own tab is the "vote" functionality. But given that voting only applies to gauges, it makes sense it lives in the tab. This organization is different from the organization of yETH, yPRISMA, and yBRIBE, but works well here.

**Comment by saltyfacu** [comment]
Already implemented
