### ISSUE TITLE
[EXT-6] FRP: [veYFI] Improve Gauge table

### ISSUE THREAD

**Issue by 0x7171** [yearn/yearn.fi#385]
### What is your proposal 🚀
This improves the columns and display of information of the table for Stake/Unstake in gauges
<img width="1209" alt="Screen Shot 2023-10-17 at 16 13 02" src="https://github.com/yearn/yearn.fi/assets/91192250/f08a90cf-47d1-4652-a95d-a0767cd35f8c">

### What does this solve ? 🛠
- Clearer info
- More accurate details
- Leads to improved usage

#### Current table structure

- Asset
- Vault APY
- Deposited
- Gauge APY
- Boost
- Staked

#### Problems with current table structure

1. Gauge APY should be APR, as it's not compounding
2. Gauge APR will be a range, between 1-10x (depending on user boost), so if the 1x boost APR is 5%, then it would display as 5% → 50%  
3. Boost column makes no sense as it's per individual user, not universal

#### New table structure

- Asset
- Vault APY
- Deposited in vault
- Gauge APR (showing values like so: `5% → 50%`)
- Staked in Gauge
- Boost (`N/A` if not staked in gauge, `1.74x` if you are staked in gauge earning 1.78x boost)

<sub>[EXT-6](https://linear.app/fancy-xopowo/issue/EXT-6/frp-[veyfi]-improve-gauge-table)</sub>

**Comment by saltyfacu** [comment]
Already implemented
