### ISSUE TITLE
[EXT-5] FRP: Fewer clicks to select a single network

### ISSUE THREAD

**Issue by dudesahn** [yearn/yearn.fi#400]
### What is your proposal 🚀

Currently, by default all networks are shown. If a user does not want to see all networks, it is likely their next choice would be to see only a single network. The current default behavior would require a user to click `All` to unselect all networks, then click on the network they desire.

I propose instead:

- default all selected (current default)
- X button on far right to remove specific network from those selected (current checkmark behavior)
- clicking anywhere else in the box highlights it as the only network selected, removing all other networks

### What does this solve ? 🛠

When using the new site, my instinct to see only Optimism vaults is to click "OP Mainnet" in the dropdown as that's how it always was before. I think this is a nice workaround that will avoid extra clicks for a lot of users and make the experience more smooth.

### More 🔎

<img width="432" alt="Screen Shot 2023-10-23 at 9 40 29 AM" src="https://github.com/yearn/yearn.fi/assets/23222916/0732fc23-3d2f-4212-b90e-e47bcd73cfbf">

<sub>[EXT-5](https://linear.app/fancy-xopowo/issue/EXT-5/frp-fewer-clicks-to-select-a-single-network)</sub>

**Comment by saltyfacu** [comment]
@evankox feel free to check this out

**Comment by karelianpie** [comment]
Done with https://github.com/yearn/yearn.fi/pull/423
