### ISSUE TITLE
FRP: for strategy name pull in the name in meta if exists

### ISSUE THREAD

**Issue by DarkGhost7** [yearn/yearn.fi#94]
### What is your proposal 🚀
I currently see this one [the website ui](https://yearn.finance/vaults/1/0xa354F35829Ae975e850e23e9615b11Da1B3dC4DE) 
![image](https://user-images.githubusercontent.com/38810205/223841709-594d5196-f946-4f06-9143-daa1664d6d78.png)

you can see that is using the smart contract name and not the `name` field in meta. 
For example this strategy should be called `Idle Finance Reinvest` not `StrategyIdleV2 IdleUSDC v4 [Best yield]`

### What does this solve ? 🛠
Use nicer looking names for strategies, also if the meta file doesn't exist it can revert back to the strategy contract name.

**Comment by karelianpie** [comment]
If we go https://etherscan.io/address/0x66f7b6e7eb858075d6f2c5615f22659a1a20f6d6 we see that the name of the strategy is indeed "StrategyIdleV2 IdleUSDC v4 [Best yield]", the "Idle Finance Reinvest" https://github.com/yearn/ydaemon/blob/develop/data/meta/strategies/1/IdleReinvest.json is the name of the group which includes `0x66f7b6E7EB858075d6F2c5615F22659a1A20f6D6`

<img width="1236" alt="Screenshot 2023-03-09 at 7 53 02" src="https://user-images.githubusercontent.com/78794805/223932602-9b80ef30-2a4f-4c33-847b-cef569f5aabc.png">
